# Generated by Django 3.0.8 on 2020-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=110)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('campony', models.CharField(blank=True, max_length=110)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='imgFile/')),
                ('phone', models.CharField(blank=True, max_length=110)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=110)),
                ('instegram', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('smtpemail', models.CharField(blank=True, max_length=110)),
                ('smtpserver', models.CharField(blank=True, max_length=255)),
                ('smtppasword', models.CharField(blank=True, max_length=255)),
                ('smtpport', models.CharField(blank=True, max_length=255)),
                ('aboutus', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
