# Generated by Django 3.0.8 on 2020-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200712_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='refrans',
            new_name='references',
        ),
    ]
