# Generated by Django 3.0.8 on 2020-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200712_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='Aumainpic',
            field=models.ImageField(blank=True, upload_to='imgFile/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='Ausidepic',
            field=models.ImageField(blank=True, upload_to='imgFile/'),
        ),
    ]
