# Generated by Django 3.0.8 on 2020-07-12 12:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200712_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rflocation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
