# Generated by Django 3.0.8 on 2020-07-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contact_MSJ',
        ),
    ]
