# Generated by Django 3.0.8 on 2020-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200712_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_msj',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
